name: Build and Publish to npm

on:
  workflow_dispatch:  # 手动触发
    inputs:
      version:
        description: "Package version (e.g., 1.0.0)"
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"  # 或私有 npm 仓库地址

      - name: List files in current directory before changing to python
        run: ls .

      - name: Change directory, remove dist folder, install dependencies, update version in package.json, and build TypeScript
        run: |
          cd typescript
          pwd
          if [ -d "dist" ]; then
            rm -rf dist/
          fi
          npm install
          npm install -g typescript  # 如果未安装全局 tsc
          npm version ${{ inputs.version }} --no-git-tag-version
          npm run build
          ls dist/

      - name: Publish to npm
        if: ${{ inputs.version != '' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd typescript
          npm publish
